---
swagger: "2.0"
info:
  description: "API for the Careflow platform for development of the frontend. The\
    \ api format conforms to JSON:API format except the public pages for log in and\
    \ sign ups. "
  version: "1.0.0"
  title: "Careflow API"
  contact:
    name: "Kariuki Gathitu"
    email: "kariuki@zegetech.com"
consumes:
- "application/json"
produces:
- "application/json"
security:
- JWT: []
paths:
  /signup:
    post:
      tags:
      - "Users"
      summary: "Sign up"
      description: "Sign up to the platform"
      consumes: []
      parameters:
      - name: "invite_token"
        in: "query"
        required: false
        type: "string"
        x-example: "sda8f9d7f0asdf7a90d7f0a"
      - name: "Authorization"
        in: "header"
        required: false
        type: "string"
      - name: "body"
        in: "body"
        required: true
        schema:
          type: "object"
          properties:
            name:
              type: "string"
              description: "James Bond"
            email:
              type: "string"
              description: "james@Mi7.com"
            password:
              type: "string"
              description: "bondjamesbond"
            confirm_password:
              type: "string"
              description: "bondjamesbond"
            invite_token:
              type: "string"
              description: "897sdfasd8fa09s8f789ds"
          description: "New user signs up to the platform"
      responses:
        200:
          description: "Successful creation of user"
          schema:
            required:
            - "data"
            type: "object"
            description: "JSON:API formatted output"
            properties:
              data:
                $ref: "#/definitions/User"
              errors:
                type: "object"
              meta:
                type: "object"
          examples:
            application/json: "{\n  \"data\": {\n    \"type\": \"user\",\n    \"id\"\
              : \"1\",\n    \"name\": \"Joe dimagio\",\n    \"email\": \"joe@careflow.com\"\
              \n  }\n}"
  /sign_in:
    post:
      summary: "Sign in"
      description: "Sign into the platform"
      consumes: []
      parameters:
      - name: "Authorization"
        in: "header"
        required: false
        type: "string"
      - name: "body"
        in: "body"
        required: true
        schema:
          type: "object"
          properties:
            email:
              type: "string"
            password:
              type: "string"
      responses:
        200:
          description: "Status 200"
  /users/password: {}
  /users:
    get:
      summary: "Get user data"
      parameters:
      - name: "Authorization"
        in: "header"
        required: false
        type: "string"
      responses:
        200:
          description: "Status 200"
          schema:
            type: "object"
            properties:
              data:
                $ref: "#/definitions/User"
    delete:
      summary: "Cancel user account"
      parameters:
      - name: "Authorization"
        in: "header"
        required: false
        type: "string"
      responses:
        204:
          description: "Status 204"
    patch:
      summary: "Updat user data"
      consumes: []
      parameters:
      - name: "Authorization"
        in: "header"
        required: false
        type: "string"
      - name: "body"
        in: "body"
        required: true
        schema:
          type: "object"
          properties:
            data:
              $ref: "#/definitions/User"
      responses:
        202:
          description: "Modification accepted"
          schema:
            type: "object"
            properties:
              data:
                $ref: "#/definitions/User"
  /users/_/{switch}:
    patch:
      summary: "Switch or toggle user states"
      parameters:
      - name: "Authorization"
        in: "header"
        required: false
        type: "string"
      responses:
        200:
          description: "Status 200"
    parameters:
    - name: "switch"
      in: "path"
      required: true
      type: "string"
      x-example: "accept_invite"
  /firebasebucket/images/avatar_{user_id}_{user_name}:
    parameters:
    - name: "user_id"
      in: "path"
      required: true
      type: "string"
    - name: "user_name"
      in: "path"
      required: true
      type: "string"
  /documents: {}
  /documents/{id}:
    parameters:
    - name: "id"
      in: "path"
      required: true
      type: "string"
  /documents/_/{switch}:
    parameters:
    - name: "switch"
      in: "path"
      required: true
      type: "string"
      x-example: "publish"
  /documents/1/_/{switch}:
    parameters:
    - name: "switch"
      in: "path"
      required: true
      type: "string"
      x-example: "publish"
  /firestore/user/{user_id}/document:
    parameters:
    - name: "user_id"
      in: "path"
      required: true
      type: "string"
  /firestore/user/{user_id}/document/{document_id}:
    parameters:
    - name: "user_id"
      in: "path"
      required: true
      type: "string"
    - name: "document_id"
      in: "path"
      required: true
      type: "string"
  /contracts: {}
  /contracts/{contract_id}:
    parameters:
    - name: "contract_id"
      in: "path"
      required: true
      type: "string"
  /contracts/1/_/{switch}:
    parameters:
    - name: "switch"
      in: "path"
      required: true
      type: "string"
      x-example: "accept"
  /notifications: {}
  /notification/{id}:
    parameters:
    - name: "id"
      in: "path"
      required: true
      type: "string"
  /notification/{id}/_/{switch}:
    parameters:
    - name: "id"
      in: "path"
      required: true
      type: "string"
    - name: "switch"
      in: "path"
      required: true
      type: "string"
      x-example: "seed"
  /activities: {}
securityDefinitions:
  JWT:
    description: "JWT token authentication. Carries session information like user.\
      \ https://jwt.io/"
    type: "apiKey"
    name: "Authorization"
    in: "header"
definitions:
  User:
    type: "object"
    required:
    - "avatar"
    - "birth_date"
    - "id"
    - "mobile_no"
    - "name"
    properties:
      id:
        type: "integer"
      name:
        type: "string"
        example: "kiki lolo"
      birth_date:
        type: "string"
        format: "date"
      mobile_no:
        type: "string"
      email:
        type: "string"
      avatar:
        type: "string"
      address_data:
        type: "object"
      pin_no:
        type: "string"
      invitation:
        type: "object"
      invited_by_id:
        type: "integer"
      caregiver_type:
        type: "string"
      position:
        type: "string"
      role:
        type: "string"
      profile:
        type: "object"
      status:
        type: "string"
  Document:
    type: "object"
    properties:
      id:
        type: "integer"
      caregiver_id:
        type: "integer"
      attached_to_id:
        type: "integer"
      attached_to_type:
        type: "string"
      pos:
        type: "integer"
      group:
        type: "string"
      name:
        type: "string"
      type:
        type: "string"
      expiry_date:
        type: "string"
        format: "date"
      verification_status:
        type: "string"
      tags:
        type: "array"
        items:
          type: "string"
      data:
        type: "object"
      dependancies:
        type: "object"
      authorizers:
        type: "object"
      verifiers:
        type: "object"
      triggers:
        type: "object"
    description: "Documents that are attacehd to a caregiers account and are tracked\
      \ for validity and currentness"
  Contract:
    type: "object"
    properties:
      id:
        type: "integer"
      caregiver_id:
        type: "integer"
      agency_id:
        type: "integer"
      hire_date:
        type: "string"
        format: "date"
      position:
        type: "string"
      status:
        type: "string"
      data:
        type: "object"
      checklist:
        type: "object"
    description: "Contract between caregivers and agencies"
  Activity:
    type: "object"
    properties:
      id:
        type: "integer"
      caregiver_id:
        type: "integer"
      occurence_id:
        type: "integer"
      occurence_type:
        type: "string"
      group_id:
        type: "integer"
      name:
        type: "string"
      to_start_at:
        type: "string"
        format: "date-time"
      to_end_at:
        type: "string"
        format: "date-time"
      started_at:
        type: "string"
        format: "date-time"
      ended_at:
        type: "string"
        format: "date-time"
      data:
        type: "object"
    description: "An actitivy describes an event in time or just a notification"
  Notification:
    type: "object"
    properties:
      id:
        type: "integer"
      group_id:
        type: "integer"
      to:
        type: "integer"
      originate_id:
        type: "integer"
        description: "polymorphic reference: from"
      originate_type:
        type: "string"
      send_time:
        type: "string"
        format: "date-time"
      message:
        type: "string"
      status:
        type: "string"
      type:
        type: "string"
    description: "Notifications to an activity. Can also be used as a messaging model\
      \ with the to and from "
  Station:
    type: "object"
    properties:
      id:
        type: "integer"
      contract_id:
        type: "integer"
      agency_id:
        type: "integer"
      room_id:
        type: "integer"
      facility_id:
        type: "integer"
      start_date:
        type: "string"
        format: "date"
      end_date:
        type: "string"
        format: "date"
      prior_station_id:
        type: "integer"
      onward_station_id:
        type: "integer"
      supervisor_id:
        type: "integer"
      room_data:
        type: "object"
      facility_data:
        type: "object"
      agency_data:
        type: "object"
    description: "This model corresponsds to a caregivers station which is a room\
      \ and facility. "
  Assignment:
    type: "object"
    properties:
      caregiver_id:
        type: "integer"
      person_id:
        type: "integer"
      person_data:
        type: "object"
      station_id:
        type: "integer"
      status:
        type: "string"
      start_date:
        type: "string"
        format: "date"
      end_date:
        type: "string"
    description: "Assignment of a caregiver to a person under care. "