---
swagger: "2.0"
info:
  description: "API for the Careflow platform for development of the frontend. The\
    \ api format conforms to JSON:API format except the public pages for log in and\
    \ sign ups. "
  version: "1.0.0"
  title: "Careflow API"
  contact:
    name: "Kariuki Gathitu"
    email: "kariuki@zegetech.com"
host: "104.196.250.49"
schemes:
- "http"
consumes:
- "application/json"
produces:
- "application/json"
paths:
  /sign_up:
    post:
      tags:
      - "Authentication"
      summary: "Sign up"
      description: "Sign up to the platform"
      consumes:
      - "application/json"
      parameters:
      - name: "body"
        in: "body"
        required: true
        schema:
          type: "object"
        x-examples:
          application/json: "{\n    \"data\": {\n        \"type\": \"users\",\n  \
            \      \"attributes\": {\n            \"name\": \"John Kilometer\",\n\
            \            \"email\": \"kili@polo9.com\",\n            \"password\"\
            : \"usadoifuosdf\"\n        }\n    }\n}"
      responses:
        200:
          description: "Status 200"
          schema:
            type: "object"
          examples:
            application/json: "{\n    \"data\": {\n        \"id\": 44,\n        \"\
              type\": \"users\",\n        \"attributes\": {\n            \"email\"\
              : \"kiki@lolo11.com\",\n            \"created_at\": \"2017-12-14T14:12:31.086Z\"\
              \n        }\n    }\n}"
        422:
          description: "Status 422"
          schema:
            type: "object"
            description: "errors with array of error objects"
          examples:
            application/json: "{\n    \"errors\": {\n        \"email\": [\n      \
              \      \"has already been taken\"\n        ]\n    }\n}"
      security:
      - API Headers: []
  /sign_in:
    post:
      tags:
      - "Authentication"
      summary: "Sign in"
      description: "Sign into the platform"
      consumes: []
      parameters:
      - name: "body"
        in: "body"
        required: true
        schema:
          type: "object"
        x-examples:
          application/json: "{\n\t\"user\" :\n\t{\n\t\t\"email\":\"kiki@lolo4.com\"\
            ,\n\t\t\"password\":\"kikiloloo\"\n\t}\n}"
      responses:
        200:
          description: "Status 200"
          schema:
            type: "object"
          examples:
            application/json: "{\n    \"data\": {\n        \"id\": 111,\n        \"\
              type\": \"users\",\n        \"attributes\": {\n            \"name\"\
              : \"John Kilometer\",\n            \"email\": \"kili@polo5.com\",\n\
              \            \"created_at\": \"2017-12-21T11:22:43.218Z\"\n        }\n\
              \    }\n}"
          headers:
            Authorization:
              type: "string"
              description: "JWT token"
              x-example: "Bearer eyJhbGciOiJIUzI1NiJ9.eyJqdGkiOiIwZGE3Y2E0Yy1lMTViLTQ5ZDUtODBiNy1hNjZmMTAxOWIyN2IiLCJmb28iOiJiYXIiLCJzdWIiOiIxIiwic2NwIjoidXNlciIsImF1ZCI6bnVsbCwiaWF0IjoxNTEzNzY3MDA3LCJleHAiOjE1MTM3NzA2MDd9.dnjKmusPb7ku-VY97pf71DV0bYSGdyjjKjJJUoUBV7s"
            Access-Control-Expose-Headers:
              type: "string"
              description: "Allow authorization header"
              x-example: "authorization"
      security:
      - API Headers: []
  /sign_out:
    delete:
      tags:
      - "Authentication"
      - "Pending"
      description: "Sign out"
      parameters:
      - name: "Authorization"
        in: "header"
        required: false
        type: "string"
        description: "Active JWT token"
        x-example: "Bearer eyJhbGciOiJIUzI1NiJ9.eyJqdGkiOiIwZGE3Y2E0Yy1lMTViLTQ5ZDUtODBiNy1hNjZmMTAxOWIyN2IiLCJmb28iOiJiYXIiLCJzdWIiOiIxIiwic2NwIjoidXNlciIsImF1ZCI6bnVsbCwiaWF0IjoxNTEzNzY3MDA3LCJleHAiOjE1MTM3NzA2MDd9.dnjKmusPb7ku-VY97pf71DV0bYSGdyjjKjJJUoUBV7s"
      responses:
        202:
          description: "Status 202"
      security: []
  /password:
    post:
      summary: "Reset Password"
      description: "Reset password for certain email"
      consumes: []
      parameters:
      - name: "body"
        in: "body"
        required: true
        schema:
          type: "object"
        x-examples:
          application/json: "{\n\t\"user\" :\n\t{\n\t\t\"email\":\"kili@polo10.com\"\
            \n\t}\n}"
      responses:
        204:
          description: "Status 204"
          schema:
            type: "object"
          examples:
            application/json: "{\n    \"data\": null\n}"
      security:
      - API Headers: []
    patch:
      summary: "Update password"
      consumes: []
      parameters:
      - name: "body"
        in: "body"
        required: true
        schema:
          type: "object"
        x-examples:
          application/json: "{\n\t\"user\" :\n\t{\n\t\t\"password\":\"newpassword\"\
            ,\n\t\t\"password_confirmation\":\"newpassword\",\n\t\t\"reset_password_token\"\
            : \"htMbxyg6hG1icnPx6HpS\"\n\t}\n}"
      responses:
        204:
          description: "Status 204"
        422:
          description: "Status 422"
          schema:
            type: "object"
          examples:
            application/json: "{\n    \"errors\": {\n        \"reset_password_token\"\
              : [\n            \"is invalid\"\n        ]\n    }\n}"
      security:
      - API Headers: []
  /confirmation:
    get:
      summary: "Confirm"
      parameters:
      - name: "confirmation_token"
        in: "query"
        required: false
        type: "string"
        x-example: "987897f987f98ds7affa"
      responses:
        200:
          description: "Status 200"
          schema:
            type: "object"
          examples:
            application/json: "{\n    \"data\": null\n}"
      security:
      - API Headers: []
    post:
      summary: "Resend confirmation"
      consumes: []
      parameters:
      - name: "body"
        in: "body"
        required: true
        schema:
          type: "object"
        x-examples:
          application/json: " {\n    \"user\": {\n         \"email\": \"kili@polo9.com\"\
            \n    }\n}\n"
      responses:
        204:
          description: "Status 204"
      security:
      - API Headers: []
  /users/{id}:
    get:
      tags:
      - "Users"
      summary: "Get user data"
      parameters: []
      responses:
        200:
          description: "Status 200"
          schema:
            type: "object"
          examples:
            application/json: "{\n\t\"data\": {\n\t\t\"id\": 44,\n\t\t\"type\": \"\
              users\",\n\t\t\"attributes\": {\n\t\t\t\"jti\": \"0da7ca4c-e15b-49d5-80b7-a66f1019b27b\"\
              ,\n\t\t\t\"first_name\": \"Kiki\",\n\t\t\t\"last_name\": \"Lolo\",\n\
              \t\t\t\"birth_date\": \"01-01-1965\",\n\t\t\t\"mobile_no\": 854576873478,\n\
              \t\t\t\"avatar\": null,\n\t\t\t\"address_data\": \"71 Pilgrim Avenue\
              \ Chevy Chase, MD 20815\",\n\t\t\t\"pin_no\": null,\n\t\t\t\"invitation\"\
              : null,\n\t\t\t\"invited_by_id\": null,\n\t\t\t\"caregiver_type\": \"\
              null\",\n\t\t\t\"position\": \"Caregiver II\",\n\t\t\t\"role\": null,\n\
              \t\t\t\"data\": null,\n\t\t\t\"status\": null,\n\t\t\t\"lock_version\"\
              : 3,\n\t\t\t\"created_at\": \"2017-12-20T09:48:13.023Z\",\n\t\t\t\"\
              updated_at\": \"2017-12-20T10:50:07.625Z\",\n\t\t\t\"email\": \"kiki@lolo11.com\"\
              ,\n\t\t\t\"created_at\": \"2017-12-14T14:12:31.086Z\"\n\t\t}\n\t}\n}"
    delete:
      tags:
      - "Users"
      summary: "Cancel user account"
      parameters: []
      responses:
        204:
          description: "Status 204"
    patch:
      tags:
      - "Users"
      summary: "Update user data"
      consumes: []
      parameters:
      - name: "body"
        in: "body"
        required: true
        schema:
          type: "object"
          properties:
            data:
              $ref: "#/definitions/User"
        x-examples:
          application/json: "{\n\t\"data\": {\n\t\t\"id\": 44,\n\t\t\"type\": \"users\"\
            ,\n\t\t\"attributes\": {\n\t\t\t\"first_name\": null,\n\t\t\t\"last_name\"\
            : null,\n\t\t\t\"birth_date\": null,\n\t\t\t\"mobile_no\": null,\n\t\t\
            \t\"created_at\": \"2017-12-20T09:48:13.023Z\",\n\t\t\t\"updated_at\"\
            : \"2017-12-20T10:50:07.625Z\",\n\t\t\t\"email\": \"kiki@lolo11.com\"\
            ,\n\t\t\t\"created_at\": \"2017-12-14T14:12:31.086Z\"\n\t\t}\n\t}\n}"
      responses:
        202:
          description: "Modification accepted"
          schema:
            type: "object"
          examples:
            application/json: "{\n\t\"data\": {\n\t\t\"id\": 44,\n\t\t\"type\": \"\
              users\",\n\t\t\"attributes\": {\n\t\t\t\"jti\": \"0da7ca4c-e15b-49d5-80b7-a66f1019b27b\"\
              ,\n\t\t\t\"first_name\": null,\n\t\t\t\"last_name\": null,\n\t\t\t\"\
              birth_date\": null,\n\t\t\t\"mobile_no\": null,\n\t\t\t\"avatar\": null,\n\
              \t\t\t\"address_data\": null,\n\t\t\t\"pin_no\": null,\n\t\t\t\"invitation\"\
              : null,\n\t\t\t\"invited_by_id\": null,\n\t\t\t\"caregiver_type\": null,\n\
              \t\t\t\"position\": null,\n\t\t\t\"role\": null,\n\t\t\t\"data\": null,\n\
              \t\t\t\"status\": null,\n\t\t\t\"lock_version\": 3,\n\t\t\t\"created_at\"\
              : \"2017-12-20T09:48:13.023Z\",\n\t\t\t\"updated_at\": \"2017-12-20T10:50:07.625Z\"\
              ,\n\t\t\t\"email\": \"kiki@lolo11.com\",\n\t\t\t\"created_at\": \"2017-12-14T14:12:31.086Z\"\
              \n\t\t}\n\t}\n}"
    parameters:
    - name: "id"
      in: "path"
      required: true
      type: "string"
  /users/{id}/{switch}:
    patch:
      tags:
      - "Users"
      summary: "Switch or toggle user states"
      parameters: []
      responses:
        200:
          description: "Status 200"
        422:
          description: "Status 422"
    parameters:
    - name: "id"
      in: "path"
      required: true
      type: "string"
    - name: "switch"
      in: "path"
      required: true
      type: "string"
  /firebasebucket/images/avatar_{user_id}_{user_name}:
    parameters:
    - name: "user_id"
      in: "path"
      required: true
      type: "string"
    - name: "user_name"
      in: "path"
      required: true
      type: "string"
  /documents:
    post:
      tags:
      - "Documents"
      summary: "Create document"
      consumes: []
      parameters:
      - name: "body"
        in: "body"
        required: true
        schema:
          type: "object"
        x-examples:
          application/json: "{\n\t\"data\": {\n\t\t\"type\": \"documents\",\n\t\t\"\
            id\": \"09f9a8sf08das09f8d\",\n\t\t\"attributes\": {\n\t\t\t\"name\":\
            \ \"Driving license\",\n\t\t\t\"document_id\": \"DL8989843\",\n\t\t\t\"\
            expiry_date\": \"2017-12-20\",\n\t\t\t\"referee\": {\n\t\t\t\t\"name\"\
            : \"John Scot\",\n\t\t\t\t\"role\": \"instructor\"\n\t\t\t},\n\t\t\t\"\
            data\": {\n\t\t\t\t\"files\": [\n\t\t\t\t\t{\n\t\t\t\t\t\t\"name\":\"\
            dl\",\n\t\t\t\t\t\t\"url\": \"firebasestore://user/1/09f9a8sf08das09f8d\"\
            \n\t\t\t\t\t}\n\t\t\t\t]\n\t\t\t}\n\t\t}\n\t}\n}\n\n"
      responses:
        200:
          description: "Status 200"
          schema:
            type: "object"
          examples:
            application/json: "{\n\t\"data\": {\n\t\t\"type\": \"documents\",\n\t\t\
              \"id\": \"09f9a8sf08das09f8d\",\n\t\t\"attributes\": {\n\t\t\t\"name\"\
              : \"Driving license\",\n\t\t\t\"document_id\": \"DL8989843\",\n\t\t\t\
              \"expiry_date\": \"2017-12-20\",\n\t\t\t\"referee\": {\n\t\t\t\t\"name\"\
              : \"John Scot\",\n\t\t\t\t\"role\": \"instructor\"\n\t\t\t},\n\t\t\t\
              \"data\": {\n\t\t\t\t\"files\": [\n\t\t\t\t\t{\n\t\t\t\t\t\t\"name\"\
              :\"dl\",\n\t\t\t\t\t\t\"url\": \"firebasestore://user/1/09f9a8sf08das09f8d\"\
              \n\t\t\t\t\t}\n\t\t\t\t]\n\t\t\t}\n\t\t}\n\t}\n}\n\n"
  /documents/{id}:
    patch:
      tags:
      - "Documents"
      summary: "Edit document"
      consumes: []
      parameters:
      - name: "body"
        in: "body"
        required: true
        schema:
          type: "object"
        x-examples:
          application/json: "{\n\t\"data\": {\n\t\t\"type\": \"documents\",\n\t\t\"\
            id\": \"09f9a8sf08das09f8d\",\n\t\t\"attributes\": {\n\t\t\t\"expiry_date\"\
            : \"2017-12-20\",\n\t\t}\n\t}\n}\n\n"
      responses:
        200:
          description: "Status 200"
          schema:
            type: "object"
          examples:
            application/json: "{\n\t\"data\": {\n\t\t\"type\": \"documents\",\n\t\t\
              \"id\": \"09f9a8sf08das09f8d\",\n\t\t\"attributes\": {\n\t\t\t\"name\"\
              : \"Driving license\",\n\t\t\t\"document_id\": \"DL8989843\",\n\t\t\t\
              \"expiry_date\": \"2017-12-20\",\n\t\t\t\"referee\": {\n\t\t\t\t\"name\"\
              : \"John Scot\",\n\t\t\t\t\"role\": \"instructor\"\n\t\t\t},\n\t\t\t\
              \"data\": {\n\t\t\t\t\"files\": [\n\t\t\t\t\t{\n\t\t\t\t\t\t\"name\"\
              :\"dl\",\n\t\t\t\t\t\t\"url\": \"firebasestore://user/1/09f9a8sf08das09f8d\"\
              \n\t\t\t\t\t}\n\t\t\t\t]\n\t\t\t}\n\t\t}\n\t}\n}\n\n"
    parameters:
    - name: "id"
      in: "path"
      required: true
      type: "string"
  /documents/_/{switch}:
    parameters:
    - name: "switch"
      in: "path"
      required: true
      type: "string"
      x-example: "publish"
  /documents/1/_/{switch}:
    parameters:
    - name: "switch"
      in: "path"
      required: true
      type: "string"
      x-example: "publish"
  /firestore/user/{user_id}/document:
    parameters:
    - name: "user_id"
      in: "path"
      required: true
      type: "string"
  /firestore/user/{user_id}/document/{document_id}:
    parameters:
    - name: "user_id"
      in: "path"
      required: true
      type: "string"
    - name: "document_id"
      in: "path"
      required: true
      type: "string"
  /contracts: {}
  /contracts/{contract_id}:
    parameters:
    - name: "contract_id"
      in: "path"
      required: true
      type: "string"
  /contracts/1/{switch}:
    parameters:
    - name: "switch"
      in: "path"
      required: true
      type: "string"
      x-example: "accept"
  /notifications: {}
  /notification/{id}:
    parameters:
    - name: "id"
      in: "path"
      required: true
      type: "string"
  /notification/{id}/{switch}:
    parameters:
    - name: "id"
      in: "path"
      required: true
      type: "string"
    - name: "switch"
      in: "path"
      required: true
      type: "string"
      x-example: "seed"
  /activities: {}
securityDefinitions:
  API Headers:
    type: "apiKey"
    name: "Accept"
    in: "header"
definitions:
  User:
    type: "object"
    required:
    - "avatar"
    - "birth_date"
    - "id"
    - "mobile_no"
    - "name"
    properties:
      id:
        type: "integer"
      name:
        type: "string"
        example: "kiki lolo"
      birth_date:
        type: "string"
        format: "date"
      mobile_no:
        type: "string"
      email:
        type: "string"
      avatar:
        type: "string"
      address_data:
        type: "object"
      pin_no:
        type: "string"
      invitation:
        type: "object"
      invited_by_id:
        type: "integer"
      caregiver_type:
        type: "string"
      position:
        type: "string"
      role:
        type: "string"
      data:
        type: "object"
      status:
        type: "string"
  Document:
    type: "object"
    properties:
      id:
        type: "integer"
      caregiver_id:
        type: "integer"
      attached_to_id:
        type: "integer"
      attached_to_type:
        type: "string"
      pos:
        type: "integer"
      group:
        type: "string"
      name:
        type: "string"
      type:
        type: "string"
      expiry_date:
        type: "string"
        format: "date"
      verification_status:
        type: "string"
      tags:
        type: "array"
        items:
          type: "string"
      data:
        type: "object"
      dependancies:
        type: "object"
      authorizers:
        type: "object"
      verifiers:
        type: "object"
      triggers:
        type: "object"
    description: "Documents that are attacehd to a caregiers account and are tracked\
      \ for validity and currentness"
  Contract:
    type: "object"
    properties:
      id:
        type: "integer"
      caregiver_id:
        type: "integer"
      agency_id:
        type: "integer"
      hire_date:
        type: "string"
        format: "date"
      position:
        type: "string"
      status:
        type: "string"
      data:
        type: "object"
      checklist:
        type: "object"
    description: "Contract between caregivers and agencies"
  Activity:
    type: "object"
    properties:
      id:
        type: "integer"
      caregiver_id:
        type: "integer"
      occurence_id:
        type: "integer"
      occurence_type:
        type: "string"
      group_id:
        type: "integer"
      name:
        type: "string"
      to_start_at:
        type: "string"
        format: "date-time"
      to_end_at:
        type: "string"
        format: "date-time"
      started_at:
        type: "string"
        format: "date-time"
      ended_at:
        type: "string"
        format: "date-time"
      data:
        type: "object"
    description: "An actitivy describes an event in time or just a notification"
  Notification:
    type: "object"
    properties:
      id:
        type: "integer"
      group_id:
        type: "integer"
      to:
        type: "integer"
      originate_id:
        type: "integer"
        description: "polymorphic reference: from"
      originate_type:
        type: "string"
      send_time:
        type: "string"
        format: "date-time"
      message:
        type: "string"
      status:
        type: "string"
      type:
        type: "string"
    description: "Notifications to an activity. Can also be used as a messaging model\
      \ with the to and from "
  Station:
    type: "object"
    properties:
      id:
        type: "integer"
      contract_id:
        type: "integer"
      agency_id:
        type: "integer"
      room_id:
        type: "integer"
      facility_id:
        type: "integer"
      start_date:
        type: "string"
        format: "date"
      end_date:
        type: "string"
        format: "date"
      prior_station_id:
        type: "integer"
      onward_station_id:
        type: "integer"
      supervisor_id:
        type: "integer"
      room_data:
        type: "object"
      facility_data:
        type: "object"
      agency_data:
        type: "object"
    description: "This model corresponsds to a caregivers station which is a room\
      \ and facility. "
  Assignment:
    type: "object"
    properties:
      caregiver_id:
        type: "integer"
      person_id:
        type: "integer"
      person_data:
        type: "object"
      station_id:
        type: "integer"
      status:
        type: "string"
      start_date:
        type: "string"
        format: "date"
      end_date:
        type: "string"
    description: "Assignment of a caregiver to a person under care. "